# Use Node.js configuration.
language: node_js

# Both latest Node.js and latest LTS.
node_js: 
  - lts/*
  - node

# All of the operating systems!
# Note: Windows support is very iffy.
os:
  - linux
  - osx
  - windows

# Also ensure that we can build installers.
script: npm test && npm run dist
